apiVersion: apps/v1
kind: Deployment
metadata:
  name: playwright-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: playwright
  template:
    metadata:
      labels:
        app: playwright
    spec:
      containers:
      - name: playwright
        image: bastabdash/playwright-e2e:latest